### ISSUE TITLE
[BUG] Error 400 when submitting two equal zips in the same dataset

### ISSUE THREAD

**Issue by nataliaaolmo** [EGC-chicharrones/chicharrones-hub-1#83]
**Describe the bug**
When two equal zips are submitted in the same dataset, the website shows error 400. 

**To Reproduce**

1. Log in as you would do normally.
2. Go to Submit Datasets
3. Submit 2 zips in the same dataset
4. Click on Submit Dataset.
5. An 400 Error will appear.

**Expected behavior**
It is expected to submit the datasets correctly and to change the name of these equal zips automatically.

**Comment by DXD-Tech** [comment]
Thanks for letting me know, Natalia! I've found a possible solution
