### ISSUE TITLE
[BUG] Search queries doesn't show all published datasets.

### ISSUE THREAD

**Issue by vDavidd** [EGC-chicharrones/chicharrones-hub-1#88]
**Describe the bug**
Search queries doesn't show all published datasets. It only fetches 4 of them.

**To Reproduce**
1. Go to upload new synchronized dataset.
2. Go to explore page.
3. See error 

**Expected behavior**
The number of found dataset should be more than 4.

**Comment by maryycarrera** [comment]
This issue is not going to be solved due to a lack of time before the last project milestone
